# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
